// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package flod

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type flodBlockval struct {
	_        structs.HostLayout
	ExpireNs uint64
}

type flodBucket struct {
	_      structs.HostLayout
	LastNs uint64
	Tokens uint32
	_      [4]byte
}

type flodLpm4 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [4]uint8
}

type flodLpm6 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [16]uint8
}

type flodSrcKey struct {
	_      structs.HostLayout
	Family uint32
	Ip     [16]uint8
}

type flodSynRateCfg struct {
	_     structs.HostLayout
	Ns    uint64
	Burst uint32
	_     [4]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	flodMapAllowQuic  = "allow_quic"
	flodMapBlock4     = "block4"
	flodMapBlock6     = "block6"
	flodMapCounts     = "counts"
	flodMapDnsRate    = "dns_rate"
	flodMapEthertypes = "ethertypes"
	flodMapNtpRate    = "ntp_rate"
	flodMapQuicRate   = "quic_rate"
	flodMapSynCfg     = "syn_cfg"
	flodMapSynRate    = "syn_rate"
	flodProgFlod      = "flod"
)

// loadFlod returns the embedded CollectionSpec for flod.
func loadFlod() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FlodBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load flod: %w", err)
	}

	return spec, err
}

// loadFlodObjects loads flod and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*flodObjects
//	*flodPrograms
//	*flodMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFlodObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadFlod()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// flodSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flodSpecs struct {
	flodProgramSpecs
	flodMapSpecs
	flodVariableSpecs
}

// flodProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flodProgramSpecs struct {
	Flod *ebpf.ProgramSpec `ebpf:"flod"`
}

// flodMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flodMapSpecs struct {
	AllowQuic  *ebpf.MapSpec `ebpf:"allow_quic"`
	Block4     *ebpf.MapSpec `ebpf:"block4"`
	Block6     *ebpf.MapSpec `ebpf:"block6"`
	Counts     *ebpf.MapSpec `ebpf:"counts"`
	DnsRate    *ebpf.MapSpec `ebpf:"dns_rate"`
	Ethertypes *ebpf.MapSpec `ebpf:"ethertypes"`
	NtpRate    *ebpf.MapSpec `ebpf:"ntp_rate"`
	QuicRate   *ebpf.MapSpec `ebpf:"quic_rate"`
	SynCfg     *ebpf.MapSpec `ebpf:"syn_cfg"`
	SynRate    *ebpf.MapSpec `ebpf:"syn_rate"`
}

// flodVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flodVariableSpecs struct {
}

// flodObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFlodObjects or ebpf.CollectionSpec.LoadAndAssign.
type flodObjects struct {
	flodPrograms
	flodMaps
	flodVariables
}

func (o *flodObjects) Close() error {
	return _FlodClose(
		&o.flodPrograms,
		&o.flodMaps,
	)
}

// flodMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFlodObjects or ebpf.CollectionSpec.LoadAndAssign.
type flodMaps struct {
	AllowQuic  *ebpf.Map `ebpf:"allow_quic"`
	Block4     *ebpf.Map `ebpf:"block4"`
	Block6     *ebpf.Map `ebpf:"block6"`
	Counts     *ebpf.Map `ebpf:"counts"`
	DnsRate    *ebpf.Map `ebpf:"dns_rate"`
	Ethertypes *ebpf.Map `ebpf:"ethertypes"`
	NtpRate    *ebpf.Map `ebpf:"ntp_rate"`
	QuicRate   *ebpf.Map `ebpf:"quic_rate"`
	SynCfg     *ebpf.Map `ebpf:"syn_cfg"`
	SynRate    *ebpf.Map `ebpf:"syn_rate"`
}

func (m *flodMaps) Close() error {
	return _FlodClose(
		m.AllowQuic,
		m.Block4,
		m.Block6,
		m.Counts,
		m.DnsRate,
		m.Ethertypes,
		m.NtpRate,
		m.QuicRate,
		m.SynCfg,
		m.SynRate,
	)
}

// flodVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFlodObjects or ebpf.CollectionSpec.LoadAndAssign.
type flodVariables struct {
}

// flodPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFlodObjects or ebpf.CollectionSpec.LoadAndAssign.
type flodPrograms struct {
	Flod *ebpf.Program `ebpf:"flod"`
}

func (p *flodPrograms) Close() error {
	return _FlodClose(
		p.Flod,
	)
}

func _FlodClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed flod_bpfel.o
var _FlodBytes []byte
